name: flutter_application_1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gif: ^2.3.0
  dio: 
  retrofit: 
  json_annotation: ^4.4.0
  built_value: ^8.0.4
  built_collection: ^5.0.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: 
  build_runner: 
  built_value_generator: ^8.0.4


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
