name: Deploy to S3 on dev branch

on:
  push:
    branches:
      - dev 
    paths:
      - 'flutter_application_1/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Build Flutter Web
        run: |
          cd flutter_application_1  
          flutter pub get       
          flutter build web      



      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::676206908438:role/gitHubActionsRole
          aws-region: us-east-1 

      - name: Sync files to S3
        run: |
          ls -la
          cd flutter_application_1 
          aws s3 sync build/web s3://glodnykotchyba --delete 
