name: Deploy to S3 on dev branch

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write 
      contents: read  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get 

      - name: Build Flutter Web
        run: flutter build web  


      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::676206908438:role/gitHubActionsRole
          aws-region: us-east-1 

      - name: Sync files to S3
        run: |
          aws s3 sync build/web s3://glodnykotchyba --delete 
