name: Deploy architecture with Terraform

on:
  push:
    branches:
      - change_zip_logic_for_lambdas

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read  # Zmienione na read, bo nie potrzebujesz zapisu
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::676206908438:role/gitHubActionsRole
        aws-region: "us-east-1"

    - name: Terraform Init and Plan
      run: |
        cd terraform/dev
        terraform init
        terraform plan -out=tfplan

  deploy:
    needs: plan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read  # Zmienione na read, bo nie potrzebujesz zapisu
      id-token: write

    steps:
    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::676206908438:role gitHubActionsRole
        aws-region: "us-east-1"

    - name: Wait for approval
      uses: hmarr/auto-approve-action@v2
      with:
        comment: "Please approve the deployment."

    - name: Apply Terraform changes
      run: |
        cd terraform/dev
        terraform apply -auto-approve tfplan
